export type User = {
  id: number;
  name: string;
  surname: string;
  email: string;
  gender: "Male" | "Female";
  ip: string;
};
export const users: User[] = [
  {
    id: 1,
    name: "Herman",
    surname: "Canas",
    email: "hcanas0@reference.com",
    gender: "Male",
    ip: "230.144.240.17",
  },
  {
    id: 2,
    name: "Vilhelmina",
    surname: "Jeannesson",
    email: "vjeannesson1@fc2.com",
    gender: "Female",
    ip: "201.121.188.167",
  },
  {
    id: 3,
    name: "Shir",
    surname: "Smeuin",
    email: "ssmeuin2@columbia.edu",
    gender: "Female",
    ip: "144.58.51.74",
  },
  {
    id: 4,
    name: "Lelah",
    surname: "Tuley",
    email: "ltuley3@chron.com",
    gender: "Female",
    ip: "220.85.75.205",
  },
  {
    id: 5,
    name: "Selle",
    surname: "Annott",
    email: "sannott4@reuters.com",
    gender: "Female",
    ip: "183.140.58.220",
  },
  {
    id: 6,
    name: "Noni",
    surname: "Sprigg",
    email: "nsprigg5@ebay.com",
    gender: "Female",
    ip: "212.220.171.72",
  },
  {
    id: 7,
    name: "Marris",
    surname: "Drackford",
    email: "mdrackford6@indiatimes.com",
    gender: "Female",
    ip: "81.71.224.120",
  },
  {
    id: 8,
    name: "Skippie",
    surname: "Ambroz",
    email: "sambroz7@va.gov",
    gender: "Male",
    ip: "118.78.186.211",
  },
  {
    id: 9,
    name: "Gerta",
    surname: "De Wolfe",
    email: "gdewolfe8@sbwire.com",
    gender: "Female",
    ip: "30.157.225.2",
  },
  {
    id: 10,
    name: "Stacee",
    surname: "Edward",
    email: "sedward9@forbes.com",
    gender: "Male",
    ip: "236.202.242.233",
  },
  {
    id: 11,
    name: "Genia",
    surname: "Bexley",
    email: "gbexleya@google.fr",
    gender: "Female",
    ip: "128.166.186.15",
  },
  {
    id: 12,
    name: "Lon",
    surname: "Herreran",
    email: "lherreranb@blogs.com",
    gender: "Male",
    ip: "2.250.112.24",
  },
  {
    id: 13,
    name: "Sawyer",
    surname: "Pagden",
    email: "spagdenc@bbb.org",
    gender: "Male",
    ip: "13.117.165.226",
  },
  {
    id: 14,
    name: "Samaria",
    surname: "McEllen",
    email: "smcellend@usatoday.com",
    gender: "Female",
    ip: "125.249.184.161",
  },
  {
    id: 15,
    name: "Ingrid",
    surname: "Sambrook",
    email: "isambrooke@boston.com",
    gender: "Female",
    ip: "46.170.176.182",
  },
  {
    id: 16,
    name: "Beatrix",
    surname: "Tabb",
    email: "btabbf@etsy.com",
    gender: "Female",
    ip: "142.130.186.125",
  },
  {
    id: 17,
    name: "Tisha",
    surname: "Hadland",
    email: "thadlandg@vinaora.com",
    gender: "Female",
    ip: "205.145.107.238",
  },
  {
    id: 18,
    name: "Virgina",
    surname: "Ogers",
    email: "vogersh@craigslist.org",
    gender: "Female",
    ip: "84.43.78.152",
  },
  {
    id: 19,
    name: "Ian",
    surname: "Huet",
    email: "ihueti@soundcloud.com",
    gender: "Male",
    ip: "39.124.93.251",
  },
  {
    id: 20,
    name: "Kin",
    surname: "Fritter",
    email: "kfritterj@sciencedirect.com",
    gender: "Male",
    ip: "31.187.185.59",
  },
  {
    id: 21,
    name: "Opal",
    surname: "Asey",
    email: "oaseyk@webnode.com",
    gender: "Female",
    ip: "42.200.242.89",
  },
  {
    id: 22,
    name: "Whitney",
    surname: "Prescot",
    email: "wprescotl@discuz.net",
    gender: "Female",
    ip: "223.44.137.191",
  },
  {
    id: 23,
    name: "Hamlin",
    surname: "Habberjam",
    email: "hhabberjamm@sbwire.com",
    gender: "Male",
    ip: "149.6.20.7",
  },
  {
    id: 24,
    name: "Sutton",
    surname: "Scotchmer",
    email: "sscotchmern@joomla.org",
    gender: "Male",
    ip: "219.91.54.104",
  },
  {
    id: 25,
    name: "Rory",
    surname: "Chadd",
    email: "rchaddo@stumbleupon.com",
    gender: "Male",
    ip: "15.225.212.1",
  },
  {
    id: 26,
    name: "Iolande",
    surname: "Danihelka",
    email: "idanihelkap@mail.ru",
    gender: "Female",
    ip: "236.132.54.92",
  },
  {
    id: 27,
    name: "Rhianon",
    surname: "Truggian",
    email: "rtruggianq@spotify.com",
    gender: "Female",
    ip: "92.55.37.249",
  },
  {
    id: 28,
    name: "Doralia",
    surname: "Oakeby",
    email: "doakebyr@mlb.com",
    gender: "Female",
    ip: "137.176.84.0",
  },
  {
    id: 29,
    name: "Ebenezer",
    surname: "Bader",
    email: "ebaders@angelfire.com",
    gender: "Male",
    ip: "192.93.232.104",
  },
  {
    id: 30,
    name: "Guntar",
    surname: "Camillo",
    email: "gcamillot@reverbnation.com",
    gender: "Male",
    ip: "172.227.174.194",
  },
];
