export const products = [
  {
    id: 1,
    name: "Tortillas - Flour, 10",
    typology: "Consumer Non-Durables",
    price: "€13,41",
  },
  { id: 2, name: "Tomatoes", typology: "Technology", price: "€10,31" },
  { id: 3, name: "Nori Sea Weed", typology: "n/a", price: "€14,65" },
  {
    id: 4,
    name: "Turnip - Wax",
    typology: "Consumer Durables",
    price: "€16,91",
  },
  {
    id: 5,
    name: "Rabbit - Frozen",
    typology: "Public Utilities",
    price: "€13,28",
  },
  {
    id: 6,
    name: "Lettuce - Spring Mix",
    typology: "Public Utilities",
    price: "€11,77",
  },
  {
    id: 7,
    name: "Silicone Parch. 16.3x24.3",
    typology: "Consumer Services",
    price: "€19,18",
  },
  {
    id: 8,
    name: "Cafe Royale",
    typology: "Consumer Services",
    price: "€18,83",
  },
  {
    id: 9,
    name: "Wine - Tio Pepe Sherry Fino",
    typology: "Consumer Durables",
    price: "€12,58",
  },
  {
    id: 10,
    name: "Grapefruit - Pink",
    typology: "Health Care",
    price: "€17,83",
  },
  {
    id: 11,
    name: "Chutney Sauce - Mango",
    typology: "Consumer Services",
    price: "€17,43",
  },
  {
    id: 12,
    name: "Flour - Fast / Rapid",
    typology: "Consumer Services",
    price: "€14,21",
  },
  { id: 13, name: "Pasta - Fusili, Dry", typology: "Energy", price: "€14,40" },
  {
    id: 14,
    name: "Yoplait - Strawbrasp Peac",
    typology: "Energy",
    price: "€11,89",
  },
  {
    id: 15,
    name: "Chef Hat 25cm",
    typology: "Consumer Services",
    price: "€18,02",
  },
  {
    id: 16,
    name: "Island Oasis - Strawberry",
    typology: "Health Care",
    price: "€16,93",
  },
  {
    id: 17,
    name: "Bread Crumbs - Japanese Style",
    typology: "Technology",
    price: "€10,09",
  },
  {
    id: 18,
    name: "Chocolate - Pistoles, Lactee, Milk",
    typology: "Finance",
    price: "€13,01",
  },
  { id: 19, name: "Garbage Bags - Black", typology: "n/a", price: "€16,13" },
  {
    id: 20,
    name: "Pie Shells 10",
    typology: "Consumer Services",
    price: "€11,57",
  },
  { id: 21, name: "Cinnamon - Ground", typology: "n/a", price: "€14,26" },
  { id: 22, name: "Puree - Pear", typology: "Technology", price: "€11,16" },
  {
    id: 23,
    name: "Noodles - Steamed Chow Mein",
    typology: "n/a",
    price: "€13,20",
  },
  {
    id: 24,
    name: "Sauce - Alfredo",
    typology: "Consumer Services",
    price: "€14,93",
  },
  {
    id: 25,
    name: "Pomegranates",
    typology: "Consumer Services",
    price: "€17,19",
  },
  { id: 26, name: "Beans - Kidney White", typology: "n/a", price: "€19,48" },
  {
    id: 27,
    name: "Cheese - Comtomme",
    typology: "Consumer Services",
    price: "€15,54",
  },
  { id: 28, name: "Avocado", typology: "Consumer Services", price: "€15,15" },
  {
    id: 29,
    name: "Coffee - Ristretto Coffee Capsule",
    typology: "n/a",
    price: "€12,90",
  },
  {
    id: 30,
    name: "Cheese - Mascarpone",
    typology: "Technology",
    price: "€14,36",
  },
];
